### ISSUE TITLE
how do I stream from OBS to nginx?

### ISSUE THREAD

**Issue by magnuszetterberg** [fschuindt/nginx_rtmp_hls_dash#1]
Hello!
Thanks for packaging this server!  

I'm able to run the ffmpeg example from your readme.md file, pushing a sample movie to your server. However, Im not able to perform the similar action through obs(though streaming a webcam and an application window for example).

Would you be able to add a instruction on how to get this working inside your readme.md file ?

**Comment by fschuindt** [comment]
@magnuszetterberg I have never tried OBS with it before, but I'm planning to do so when I have some time.
But meanwhile: I think RTMP is supported out of the box on OBS. Is it?

I imagine it would be pretty similar to this demonstration here:  
[https://support.accelevents.com/en/articles/4102301-broadcasting-with-obs-or-wirecast-through-rtmp-stream](https://support.accelevents.com/en/articles/4102301-broadcasting-with-obs-or-wirecast-through-rtmp-stream)

**Comment by ClaudioRodriguesNunes** [comment]
Correct. It behaves well for rtmp but for rtmps (send to facebook for example) it doesn't support unfortunately.

**Comment by fschuindt** [comment]
I think this solves the issue, as far as I understand, this is a problem with the OBS not supporting RTMPS, right? Does current versions already support it? I can't find much on the subject. I'm closing this for now, feel free, anyone, to re-open it.
