### ISSUE TITLE
typo in nginx.conf  

### ISSUE THREAD

**Issue by magnuszetterberg** [fschuindt/nginx_rtmp_hls_dash#2]
I guess this is a typo.

In the nginx.conf file,  the broadcast HTTP/HTTPS types refers to 
    # Broadcast HTTP/HTTPS Types
    types {
        # HLS
        application/vnd.appple.mpegurl m3u8;
        video/mp2t ts;
        
When it should refer to 
    # Broadcast HTTP/HTTPS Types
    types {
        # HLS
        application/vnd.apple.mpegurl m3u8;
        video/mp2t ts;

**Comment by fschuindt** [comment]
Thank you @magnuszetterberg, I see the "appple" typo now. :+1:
